
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[229] =
    {   0,
        0,    0,   68,   66,   64,   64,   66,   66,   55,   56,
       36,   35,   47,   34,   65,   37,   40,   49,   46,   57,
       59,   58,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   24,   54,   54,   54,   54,   54,   25,   52,
       66,   64,    0,    0,   43,    0,   50,   48,    0,   40,
        0,   45,   61,   60,   62,   54,   54,   54,   54,   54,
       54,   54,    5,   54,    0,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   23,   54,
       54,   54,   29,   54,   54,   54,   54,   54,   51,    0,
        0,   63,   44,   43,   41,   40,   54,   54,   54,   54,

       54,   54,    6,   38,    8,    7,   54,   54,   54,   54,
       54,   54,   15,   54,   54,   54,   54,   54,   54,   54,
       39,   54,   54,   27,   28,   54,   54,   54,   33,   54,
       63,    0,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       19,   54,   54,   54,   26,   53,   54,   31,   54,   54,
       41,   54,   54,   54,   54,   54,    3,   54,   54,   54,
       54,   42,   54,   54,   54,   14,   16,   54,   54,   20,
       21,   54,   30,   32,   54,    1,   54,   54,   53,   54,
       54,   53,   54,   54,   11,   54,   54,   17,   54,   54,

       54,   54,   54,   54,   54,    9,   54,   54,   54,   18,
       54,   54,   54,   53,   53,   54,   54,   12,   54,   22,
       54,    2,    4,   54,   13,   42,   10,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   29,   30,   31,   32,   33,   34,
       29,   35,   36,   37,   38,   39,   29,   29,   40,   29,
       41,    1,   42,    1,    1,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   29,   29,   52,   53,   54,
       55,   56,   29,   57,   58,   59,   60,   61,   29,   29,
       62,   29,   63,    1,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1
    } ;

static const flex_int16_t yy_base[233] =
    {   0,
        0,    0,  613,  614,   63,   65,    0,   64,  614,  614,
      614,  614,  614,  593,  599,  614,   58,  592,  614,   55,
      614,  591,   57,   61,   64,   67,   72,  113,  594,   69,
      108,   66,  593,   86,   84,   97,  140,  110,  592,  563,
       75,   90,  600,  110,  614,  115,  614,  614,  589,  163,
      588,  614,  614,  614,  614,  587,  586,  148,  141,  131,
      162,  166,  165,  167,   74,  168,  185,  170,  151,   62,
      174,  181,  207,  182,  198,  202,  199,  208,  585,  215,
      228,  225,  584,  219,  230,  235,  238,  243,  614,  179,
      221,  614,  614,  246,  242,  583,  247,  248,  254,  266,

      268,  256,  575,  572,  614,  273,  280,  282,  251,  285,
      295,  287,  571,  290,  293,  307,  298,  312,  314,  302,
      570,  318,  323,  569,  567,  327,  321,  333,  564,  344,
      266,  563,  329,  331,  336,  350,  355,  334,  358,  354,
      364,  366,  373,  360,  380,  381,  377,  384,  351,  391,
      561,  387,  394,  393,  559,  555,  412,  554,  413,  420,
      553,  415,  410,  429,  431,  409,  549,  422,  398,  427,
      436,  548,  443,  434,  444,  547,  545,  445,  450,  541,
      539,  452,  531,  527,  461,  485,  453,  459,  483,  472,
      456,  402,  463,  464,  396,  465,  475,  356,  486,  494,

      487,  490,  492,  509,  508,  309,  512,  510,  513,  296,
      516,  515,  521,  260,  188,  522,  517,  187,  524,  132,
      525,  129,  128,  532,  123,   89,   87,  614,  587,  590,
       93,  593
    } ;

static const flex_int16_t yy_def[233] =
    {   0,
      228,    1,  228,  228,  228,  228,  229,  230,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  228,
      232,  228,  228,  230,  228,  230,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  228,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  228,  232,
      232,  228,  228,  230,  228,  228,  231,  231,  231,  231,

      231,  231,  231,  231,  228,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      232,  228,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      228,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,    0,  228,  228,
      228,  228
    } ;

static const flex_int16_t yy_nxt[679] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   29,   29,   29,
       31,   32,   33,   34,   35,   36,   37,   29,   38,   39,
       40,    4,   23,   24,   25,   26,   27,   28,   29,   30,
       29,   29,   31,   32,   33,   34,   35,   36,   37,   29,
       38,   39,   41,    4,   42,   42,   42,   42,   45,   49,
       56,   50,   53,   54,   56,   56,   46,   56,   58,   56,
       56,   51,   56,   61,   65,   56,   59,   91,   76,  111,
       63,   42,   42,   60,   64,   57,   62,   56,   79,   56,

       56,   58,   56,   66,   51,   80,   61,   81,   59,  105,
       56,   76,  111,   63,   45,   60,   82,   64,   62,   94,
       79,   56,   46,   56,   83,   66,   56,   46,   80,   87,
       81,  105,   67,   88,   68,   77,   56,   69,   92,   82,
       78,   56,   56,   70,   56,   56,   71,   83,   72,   73,
       74,   75,   87,   56,   56,   67,   88,   68,   77,   84,
       69,   56,   78,   99,   56,   70,   98,   85,   71,   97,
       72,   73,   74,   75,   49,   56,   50,   86,   56,   56,
       56,   56,   84,   56,  100,   99,   51,   56,  110,   98,
       85,   91,   97,  112,   56,   56,  101,  102,   56,   86,

       56,   56,  109,  103,  106,  104,  107,  100,  113,   51,
      110,   56,   56,  116,  108,   56,  112,  117,  101,  102,
       56,   56,  120,  118,  109,  103,  106,  104,   56,  107,
      121,  113,   56,   91,  114,  116,  108,  119,   56,  126,
      117,   56,   92,   56,  115,  120,  118,  123,   56,  122,
       45,   56,  124,  121,  125,   95,   56,  114,   46,  119,
       56,   56,  126,  127,   56,  132,  115,   56,  128,   56,
      123,  122,  129,   56,  133,  124,  125,  130,   91,   56,
      134,   56,  144,  135,  131,  127,   56,  137,  132,  136,
      128,  138,  139,   56,  129,   56,  140,  133,   56,  130,

       56,  141,  134,   56,  144,  135,   56,  142,   56,   56,
      137,   56,  136,  138,  139,   56,  145,  143,  146,  140,
       56,  147,   56,  148,  141,   56,  149,   56,  150,   92,
      142,   56,  151,  154,   56,  152,   56,  155,  145,  143,
       56,  146,   56,  147,   56,  148,   56,   56,  149,   56,
      153,  150,  156,  158,  151,  154,  157,   56,  152,  164,
      155,  162,  159,   56,   56,  163,  160,   56,   56,   56,
      167,   56,  153,   56,  156,  158,  166,   56,  157,   56,
      178,  165,  164,  162,  159,  168,   56,  163,  169,  160,
       56,  170,  167,   56,   56,  173,  176,   56,  171,  166,

       56,  174,  178,  165,   56,  172,   56,   56,  168,   56,
      169,   56,  175,  181,  170,   56,  177,  173,  179,  176,
      171,  180,   56,   56,  174,   56,   56,  172,   56,  182,
      192,  183,  184,   56,  175,   56,  181,  187,  177,  185,
       56,  179,   56,  180,   56,  190,  186,   56,  188,   56,
      189,  182,  192,  191,  183,  184,   56,   56,   56,  193,
      187,  196,  185,   56,  198,   56,   56,  190,  186,   56,
      194,  188,   56,  189,   56,  191,   56,   56,   56,  195,
      197,  193,  199,  201,  196,   56,  200,  198,   56,  202,
      203,  207,  194,  205,  206,  204,   56,  208,   56,   56,

       56,  195,  197,   56,  199,   56,  201,   56,  200,  209,
      212,  202,  203,  211,  207,  205,  206,  210,  204,  208,
      213,   56,   56,   56,  214,   56,   56,  216,   56,   56,
       56,  209,  219,  212,   56,   56,  211,   56,   56,  210,
       56,  218,  213,  215,   56,   56,  214,  224,  217,  221,
      216,  220,   56,  222,   56,  219,  223,  226,   56,  225,
       56,   56,   56,  218,  227,  215,  161,   56,   56,  224,
      217,  221,   56,  220,   56,  222,  161,   56,  223,  226,
       56,  225,   56,   56,   56,   56,  227,   43,   56,   43,
       44,   44,   44,   90,   90,   90,   96,   56,   56,   56,

       56,   96,   95,   93,   89,   56,   56,   56,   55,   52,
       48,   47,  228,    3,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228
    } ;

static const flex_int16_t yy_chk[679] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    6,    8,   17,
       23,   17,   20,   20,   24,   70,    8,   25,   23,   32,
       26,   17,   30,   25,   27,   27,   23,   41,   30,   70,
       26,   42,   42,   24,   26,  231,   25,   35,   32,   34,

      227,   23,  226,   27,   17,   34,   25,   35,   23,   65,
       36,   30,   70,   26,   44,   24,   36,   26,   25,   46,
       32,   31,   44,   38,   36,   27,   28,   46,   34,   38,
       35,   65,   28,   38,   28,   31,  225,   28,   41,   36,
       31,  223,  222,   28,   60,  220,   28,   36,   28,   28,
       28,   28,   38,   37,   59,   28,   38,   28,   31,   37,
       28,   58,   31,   60,   69,   28,   59,   37,   28,   58,
       28,   28,   28,   28,   50,   61,   50,   37,   63,   62,
       64,   66,   37,   68,   61,   60,   50,   71,   69,   59,
       37,   90,   58,   71,   72,   74,   61,   62,   67,   37,

      218,  215,   68,   63,   66,   64,   67,   61,   72,   50,
       69,   75,   77,   74,   67,   76,   71,   75,   61,   62,
       73,   78,   77,   76,   68,   63,   66,   64,   80,   67,
       78,   72,   84,   91,   73,   74,   67,   76,   82,   84,
       75,   81,   90,   85,   73,   77,   76,   81,   86,   80,
       94,   87,   81,   78,   82,   95,   88,   73,   94,   76,
       97,   98,   84,   85,  109,   95,   73,   99,   86,  102,
       81,   80,   87,  214,   97,   81,   82,   88,  131,  100,
       98,  101,  109,   99,   91,   85,  106,  101,   95,  100,
       86,  102,  102,  107,   87,  108,  106,   97,  110,   88,

      112,  107,   98,  114,  109,   99,  115,  108,  111,  210,
      101,  117,  100,  102,  102,  120,  110,  108,  111,  106,
      116,  112,  206,  114,  107,  118,  115,  119,  116,  131,
      108,  122,  117,  120,  127,  118,  123,  122,  110,  108,
      126,  111,  133,  112,  134,  114,  128,  138,  115,  135,
      119,  116,  123,  127,  117,  120,  126,  130,  118,  135,
      122,  133,  128,  136,  149,  134,  130,  140,  137,  198,
      138,  139,  119,  144,  123,  127,  137,  141,  126,  142,
      149,  136,  135,  133,  128,  139,  143,  134,  140,  130,
      147,  141,  138,  145,  146,  144,  147,  148,  142,  137,

      152,  145,  149,  136,  150,  143,  154,  153,  139,  195,
      140,  169,  146,  153,  141,  192,  148,  144,  150,  147,
      142,  152,  166,  163,  145,  157,  159,  143,  162,  154,
      169,  157,  159,  160,  146,  168,  153,  163,  148,  160,
      170,  150,  164,  152,  165,  166,  162,  174,  164,  171,
      165,  154,  169,  168,  157,  159,  173,  175,  178,  170,
      163,  174,  160,  179,  178,  182,  187,  166,  162,  191,
      171,  164,  188,  165,  185,  168,  193,  194,  196,  173,
      175,  170,  179,  185,  174,  190,  182,  178,  197,  187,
      188,  194,  171,  191,  193,  190,  189,  196,  186,  199,

      201,  173,  175,  202,  179,  203,  185,  200,  182,  197,
      201,  187,  188,  200,  194,  191,  193,  199,  190,  196,
      202,  205,  204,  208,  203,  207,  209,  205,  212,  211,
      217,  197,  209,  201,  213,  216,  200,  219,  221,  199,
      184,  208,  202,  204,  183,  224,  203,  217,  207,  212,
      205,  211,  181,  213,  180,  209,  216,  221,  177,  219,
      176,  172,  167,  208,  224,  204,  161,  158,  156,  217,
      207,  212,  155,  211,  151,  213,  132,  129,  216,  221,
      125,  219,  124,  121,  113,  104,  224,  229,  103,  229,
      230,  230,  230,  232,  232,  232,   96,   83,   79,   57,

       56,   51,   49,   43,   40,   39,   33,   29,   22,   18,
       15,   14,    3,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ProAlg.l"
/*
* Scanner para proAlg por Ioar Crespo y Guillermo Berasategui
* 07/10/2019
*/
/*
* NOTA: DR_OP_REL_IGUAL tambien representa DR_CREAR_TIPO con el simbolo "="
* DUDA 2: ¿El token 'T_LITERAL' engloba a 'T_LITERAL_NUMERICO', 'T_LITERAL_BOOLEANO', 'T_LITERAL_CADENA'
*           y 'T_LITERAL_CARACTER' deberiamos devolver a bison en estos casos 'T_LITERAL' y yy.type el correspondiente
*           tipo?
*/
#line 14 "ProAlg.l"
#include <math.h>
#include "ProAlg.tab.h"
#line 680 "lex.yy.c"
#line 681 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 88 "ProAlg.l"


#line 901 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 229 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 614 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 90 "ProAlg.l"
{printf("accion: %s\n", yytext); return T_ACCION;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 92 "ProAlg.l"
{printf("algoritmo: %s\n", yytext); return T_ALGORITMO;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 94 "ProAlg.l"
{printf("const: %s\n", yytext); return T_CONSTANTE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 96 "ProAlg.l"
{printf("continuar: %s\n", yytext); return T_CONTINUAR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 98 "ProAlg.l"
{printf("de: %s\n", yytext); return T_DE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 100 "ProAlg.l"
{printf("dev: %s\n", yytext); return T_DEV;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 102 "ProAlg.l"
{printf("ent: %s\n", yytext); return T_ENT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 104 "ProAlg.l"
{printf("e/s: %s\n", yytext); return T_E_S;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 106 "ProAlg.l"
{printf("faccion: %s\n", yytext); return T_FACCION;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 108 "ProAlg.l"
{printf("falgoritmo: %s\n", yytext); return T_FALGORITMO;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 110 "ProAlg.l"
{printf("fconst: %s\n", yytext); return T_FCONST;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 112 "ProAlg.l"
{printf("ffuncion: %s\n", yytext); return T_FFUNCION;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 114 "ProAlg.l"
{printf("fmientras: %s\n", yytext); return T_FMIENTRAS;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 116 "ProAlg.l"
{printf("fpara: %s\n", yytext); return T_FPARA;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 118 "ProAlg.l"
{printf("fsi: %s\n", yytext); return T_FSI;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 120 "ProAlg.l"
{printf("ftipo: %s\n", yytext); return T_FTIPO;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 122 "ProAlg.l"
{printf("ftupla: %s\n", yytext); return T_FTUPLA;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 124 "ProAlg.l"
{printf("funcion: %s\n", yytext); return T_FUNCION;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 126 "ProAlg.l"
{printf("fvar: %s\n", yytext); return T_FVAR;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 128 "ProAlg.l"
{printf("hacer: %s\n", yytext); return T_HACER;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 130 "ProAlg.l"
{printf("hasta: %s\n", yytext); return T_HASTA;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 132 "ProAlg.l"
{printf("mientras: %s\n", yytext); return T_MIENTRAS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 134 "ProAlg.l"
{printf("no: %s\n", yytext); return T_NO;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 136 "ProAlg.l"
{printf("o: %s\n", yytext); return T_O;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 138 "ProAlg.l"
{printf("y: %s\n", yytext); return T_Y;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 140 "ProAlg.l"
{printf("para: %s\n", yytext); return T_PARA;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 142 "ProAlg.l"
{printf("ref: %s\n", yytext); return T_REF;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 144 "ProAlg.l"
{printf("sal: %s\n", yytext); return T_SAL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 146 "ProAlg.l"
{printf("si: %s\n", yytext); return T_SI;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 148 "ProAlg.l"
{printf("tabla: %s\n", yytext); return T_TABLA;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 150 "ProAlg.l"
{printf("tipo: %s\n", yytext); return T_TIPO;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 152 "ProAlg.l"
{printf("tupla: %s\n", yytext); return T_TUPLA;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 154 "ProAlg.l"
{printf("var: %s\n", yytext); return T_VAR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 156 "ProAlg.l"
{printf("Operador resta: %s\n", yytext); return T_OP_RESTA;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 158 "ProAlg.l"
{printf("Operador suma: %s\n", yytext); return T_OP_SUMA;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 160 "ProAlg.l"
{printf("Operador multiplicaión: %s\n", yytext); return T_OP_MULTI;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 162 "ProAlg.l"
{printf("operador división: %s\n", yytext); return T_OP_DIV;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 164 "ProAlg.l"
{printf("operador división entera: %s\n", yytext); return T_OP_DIV_ENT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 166 "ProAlg.l"
{printf("Operador mod: %s\n", yytext); return T_OP_MOD;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 168 "ProAlg.l"
{printf("Literal entero: %d \n", atoi(yytext)); return T_LITERAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 170 "ProAlg.l"
{printf("Literal real: %lf \n", atof(yytext)); return T_LITERAL ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 172 "ProAlg.l"
{printf("Literal booleano: %s \n", yytext); return T_LITERAL;}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 174 "ProAlg.l"
{printf( "Literal cadena: %s\n", yytext); return T_LITERAL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 176 "ProAlg.l"
{printf( "Literal caracter: %s\n", yytext); return T_LITERAL;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 178 "ProAlg.l"
{printf("Asignación: %s\n", yytext); return T_ASIGNACION;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 180 "ProAlg.l"
{printf("Composición secuencial: %s\n", yytext); return T_COMP_SECUENCIAL;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 182 "ProAlg.l"
{printf("Separador: %s\n", yytext); return T_SEPARADOR;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 184 "ProAlg.l"
{printf("Subrango: %s\n", yytext); return T_SUBRANGO;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 186 "ProAlg.l"
{printf("Definir tipos: %s\n", yytext); return T_DEF_TIPO;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 188 "ProAlg.l"
{printf("Simbolo if: %s\n", yytext); return T_SIMBOLO_BLOQUE_IF;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 190 "ProAlg.l"
{printf("Simbolo else: %s\n", yytext); return T_SIMBOLO_ELSE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 192 "ProAlg.l"
{printf("Simbolo crear tipo: %s\n", yytext); return T_INICIO_ARRAY;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 194 "ProAlg.l"
{printf("Tipo de la variable: %s\n", yytext); return T_ID;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 196 "ProAlg.l"
{printf("Identificador: %s\n", yytext ); return T_ID;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 198 "ProAlg.l"
{printf("Parentesis apertura: %s\n", yytext); return T_PARENTESIS_APERTURA;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 200 "ProAlg.l"
{printf("Parentesis clausura: %s\n", yytext); return T_PARENTESIS_CLAUSURA;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 202 "ProAlg.l"
{printf("Operador relacional menor: %s\n", yytext); return T_OP_REL_MENOR;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 204 "ProAlg.l"
{printf("Operador relacional mayor: %s\n", yytext); return T_OP_REL_MAYOR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 206 "ProAlg.l"
{printf("Operador relacional igual: %s\n", yytext); return T_OP_REL_IGUAL;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 208 "ProAlg.l"
{printf("Operador relacional diferente: %s\n", yytext); return T_OP_REL_DIF;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 210 "ProAlg.l"
{printf("Operador relacional menor o igual: %s\n", yytext); return T_OP_REL_MENOR_IGUAL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 212 "ProAlg.l"
{printf("Operador relacional mayor o igual: %s\n", yytext); return T_OP_REL_MAYOR_IGUAL;}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 214 "ProAlg.l"
{printf("Comentario: %s\n", yytext); return T_COMENTARIO;}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 216 "ProAlg.l"
{}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 218 "ProAlg.l"
{printf("Punto: %s\n", yytext); return T_PUNTO;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 220 "ProAlg.l"
{printf( "TOKEN SIN RECONOCER: %s\n", yytext );}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 222 "ProAlg.l"
ECHO;
	YY_BREAK
#line 1296 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 229 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 229 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 228);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 222 "ProAlg.l"


